[workspace]
members = [
    "cert-manager",
    "server-core",
]

[dependencies]
rustls = { version = "0.23.23", features = ["logging"] }
rcgen = "0.13.2"
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.7"
