[package]
name = "rb_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
log = "0.4.26"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"]}
simple_logger = "5.0.0"
tokio = { version = "1.44.1", features = ["full"]}
